### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by neunzehnachtneun** [lekma/plugin.video.invidious#40]
Hi all,
after a few days of working fine, yesterday the addon stopped working. Anyone knows how to fix it?

Thanks in advance!

```
2020-10-05 12:54:52.471 T:1690223488   ERROR: [plugin.video.invidious] service: error processing request: [JSONDecodeError: Expecting value: line 1 column 1 >
2020-10-05 12:54:52.478 T:1261474688   ERROR: GetDirectory - Error getting plugin://plugin.video.invidious/?action=search&q=dota%20rennrad&type=video
2020-10-05 12:54:52.483 T:1799328640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'iapc.RequestError'>
                                            Error Contents: remote traceback: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc.py", line 123, in execute
                                                response = {"result": method(*args, **kwargs)}
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 129, in query
                                                return self.get(self._urls_.get(key, key).format(*args), **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 123, in get
                                                return self._session_.get(urljoin(self._url, url), params=kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 43, in request
                                                return response.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 79, in scan_once
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 70, in _scan_once
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)

                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 219, in <module>
                                                dispatch(*sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 214, in dispatch
                                                Dispatcher(url, int(handle)).dispatch(**parseQuery(query))
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 208, in dispatch
                                               return action(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 32, in wrapper
                                                success = func(self, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 196, in search
                                                return self._search(q, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 162, in _search
                                                client.search(q, **kwargs), kwargs["type"], q=q, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/client.py", line 125, in search
                                                self.query_("search", q=q, page=page, **kwargs), limit=limit)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/client.py", line 41, in query_
                                                return self.client.query(key, *args, **kwargs) or self._defaults_.get(key, [])
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc.py", line 195, in __call__
                                                return Request(self.sender).execute((self.name, args, kwargs))
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc.py", line 174, in execute
                                                raise self.response
                                            RequestError: remote traceback: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc.py", line 123, in execute
                                                response = {"result": method(*args, **kwargs)}
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 129, in query
                                                return self.get(self._urls_.get(key, key).format(*args), **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 123, in get
                                                return self._session_.get(urljoin(self._url, url), params=kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 43, in request
                                                return response.json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 79, in scan_once
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 70, in _scan_once
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)

                                            -->End of Python script error report<--
```

**Comment by lekma** [comment]
sorry for being late.
has this been solved?

**Comment by neunzehnachtneun** [comment]
Yes, I need to uninstall netflix and invidious plugin, reinstalled both and both are working again.
