### ISSUE TITLE
ERROR Can't return videos

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#52]
The search can't return videos :

Version :
Kodi 18.9 
Invidious 0.5.3

log :

`2021-01-09 17:11:56.785 T:140646035723840  NOTICE: [plugin.video.invidious] request.url: https://invidio.us/api/v1/search?q=ls&region=US&type=video&page=1&sort_by=relevance
2021-01-09 17:11:57.146 T:140646035723840   ERROR: [plugin.video.invidious] service: error processing request: [JSONDecodeError: Expecting value: line 1 column 1 (char 0)]
2021-01-09 17:11:57.714 T:140646395389504   ERROR: GetDirectory - Error getting plugin://plugin.video.invidious/?action=search&new=True&type=video
2021-01-09 17:11:57.715 T:140645750535744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'iapc.json_service.RequestError'>
                                            Error Contents: remote traceback: Traceback (most recent call last):
                                              File "/home/USER/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 97, in execute
                                                response = {"result": method(*args, **kwargs)}
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/service.py", line 192, in query
                                                self.__paths__.get(key, key).format(*args), **kwargs
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/service.py", line 178, in __get__
                                                urljoin(self.__url__, path), timeout=self.__timeout__, params=kwargs
                                              File "/home/USER/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/service.py", line 102, in request
                                                result = response.json()
                                              File "/home/USER/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 525, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            
                                            Traceback (most recent call last):
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 223, in <module>
                                                dispatch(*sys.argv)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 219, in dispatch
                                                InvidiousPlugin(url, int(handle)).dispatch(**parseQuery(query))
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 33, in dispatch
                                                super(InvidiousPlugin, self).dispatch(**kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/tools/plugin.py", line 68, in dispatch
                                                return action(**kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/tools/plugin.py", line 29, in wrapper
                                                success = func(self, **kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 201, in search
                                                return self._new_search(history=history, **kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 189, in _new_search
                                                return self._search(query, **kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 172, in _search
                                                client.search(query, **kwargs), kwargs["type"],
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/invidious/client.py", line 156, in search
                                                self._query("search", q=query, page=page, **kwargs),
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/invidious/client.py", line 46, in _query
                                                self.__client__.query(key, *args, **kwargs) or
                                              File "/home/USER/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 174, in __call__
                                                return Request(self.sender).execute((self.name, args, kwargs))
                                              File "/home/USER/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 153, in execute
                                                raise self.response
                                            RequestError: remote traceback: Traceback (most recent call last):
                                              File "/home/USER/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 97, in execute
                                                response = {"result": method(*args, **kwargs)}
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/service.py", line 192, in query
                                                self.__paths__.get(key, key).format(*args), **kwargs
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/service.py", line 178, in __get__
                                                urljoin(self.__url__, path), timeout=self.__timeout__, params=kwargs
                                              File "/home/USER/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/home/USER/.kodi/addons/plugin.video.invidious/lib/service.py", line 102, in request
                                                result = response.json()
                                              File "/home/USER/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 525, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            
                                            -->End of Python script error report<--
2021-01-09 17:11:57.726 T:140647372338048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.invidious/?action=search&new=True&type=video) failed`

**Comment by lekma** [comment]
invidius.us is not an instance anymore.
it is redirected to a warning page, that's why you're seeing this error.
you should choose another instance.
