### ISSUE TITLE
Error when trying to do access contents with Invidious on Kodi

### ISSUE THREAD

**Issue by vanfanel** [lekma/plugin.video.invidious#55]
Hi there,

I am running KODI on the Raspberry Pi4, and I have manually installed the Invidious plugin.

However, everytime I try to do a SEARCH, or access the MUSIC section, etc... I get "Invidious error: check log"

And here's what I see in the log:

```
2021-01-31 01:55:32.874 T:2785600368  NOTICE: [plugin.video.invidious] request.url: https://invidious.snopyta.org/api/v1/search?q=laseractive&region=US&type=video&page=1&sort_by=relevance
2021-01-31 01:55:33.169 T:2785600368   ERROR: [plugin.video.invidious] service: error processing request: [HTTPError: 403 Client Error: Forbidden for url: https://invidious.snopyta.org/api/v1/search?q=laseractive&region=US&type=video&page=1&sort_by=relevance]
2021-01-31 01:55:33.247 T:2556408688 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-01-31 01:55:33.545 T:2504319856   ERROR: GetDirectory - Error getting plugin://plugin.video.invidious/?action=search&query=laseractive&sort_by=relevance&type=video
2021-01-31 01:55:33.549 T:2489844592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'iapc.json_service.RequestError'>
                                            Error Contents: remote traceback: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.iapc/lib/iapc/json_service.py", line 97, in execute
                                                response = {"result": method(*args, **kwargs)}
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 192, in query
                                                self.__paths__.get(key, key).format(*args), **kwargs
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 178, in __get__
                                                urljoin(self.__url__, path), timeout=self.__timeout__, params=kwargs
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.invidious/lib/service.py", line 100, in request
                                                raise error
                                            HTTPError: 403 Client Error: Forbidden for url: https://invidious.snopyta.org/api/v1/search?q=laseractive&region=US&type=video&page=1&sort_by=relevance
```
It goes on, etc. But I believe it must be something easy on my side, since nothing seems to work.
Any help, please?

**Comment by lekma** [comment]
snopyta.org respond with a 403 to our requests, I'll try to investigate why.
in the meantime you should set your instance to one that still answers correctly.
invidious.tube was working as of just a couple of minutes ago....

p.s.: when invidious.io becomes available it will be the new default

**Comment by vanfanel** [comment]
@lekma Thanks for your answer :)

I have tried setting invidious.tube and I get the same error.
I have also tried invidious.fn.fr without luck (google returns that instance).
So, as of now, I seem to be unable to use the plugin. Am I missing something?
