### ISSUE TITLE
Error 403 and 500 

### ISSUE THREAD

**Issue by DavidHenryThoreau** [lekma/plugin.video.invidious#59]
Error can't play any videos : 

`ERROR <general>: AddOnLog: inputstream.adaptive: Download https://r2---sn-5hne6ns6.googlevideo.com/videoplaybackt...=r2---sn-5hne6ns6.googlevideo.com failed with error: 403
2021-04-03 09:50:49.071 T:14249   ERROR <general>: AddOnLog: inputstream.adaptive: Unable to select stream!
2021-04-03 09:50:49.216 T:14251   ERROR <general>: AddOnLog: inputstream.adaptive: Download https://r2---sn-5hne6ns6.googlevideo.com/videoplayback?expire.. failed with error: 403`

Even with right click play with youtube :

`2021-04-03 09:56:18.695 T:10289   ERROR <general>: [plugin.video.invidious] <httpd> 'GET /manifest?videoId=BP3_dgTofKA HTTP/1.1' => (500 - Internal Server Error)
                                                   Traceback (most recent call last):
                                                     File "/home/USER/.kodi/addons/script.module.iapc/lib/iapc/httpd.py", line 93, in execute
                                                       return self.server.execute(self)
                                                     File "/home/USER/.kodi/addons/script.module.iapc/lib/iapc/httpd.py", line 149, in execute
                                                       result = method(**parseQuery(url.query))
                                                     File "/home/USER/.kodi/addons/plugin.video.invidious/lib/invidious/youtube/httpd.py", line 158, in manifest
                                                       video = self.video(videoId)
                                                     File "/home/USER/.kodi/addons/plugin.video.invidious/lib/invidious/youtube/httpd.py", line 121, in video
                                                       video = find(html, r"ytInitialPlayerResponse\s*=\s*")
                                                     File "/home/USER/.kodi/addons/plugin.video.invidious/lib/invidious/youtube/httpd.py", line 28, in find
                                                       raise PatternsError(*patterns)
                                                   invidious.youtube.find.PatternsError: No matches found for patterns: ('ytInitialPlayerResponse\\s*=\\s*',)
2021-04-03 09:56:18.695 T:20882   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 500
2021-04-03 09:56:18.696 T:20882   ERROR <general>: CCurlFile::Open failed with code 500 for http://127.0.0.1:58657/manifest?videoId=BP3_dgTofKA:`

**Comment by lekma** [comment]
the error 500(play from youtube) should be fixed in f3af8e5ccbafbb6f54b7eb07456bb78ad7848687
as for the 403 it can be the instance being blacklisted or returning a borked playlist...

**Comment by DavidHenryThoreau** [comment]
Great, can you publish a new release, or can you give me how can i build new version by myslelf to test it ?

**Comment by lekma** [comment]
no update for 2 months -> closing

**Comment by art-ist** [comment]
Yep, for me this did the trick for me. Thanks @lekma.

The preconfigured default instance seems not to be working. After changing to one of the instances from the [list](https://api.invidious.io/?sort_by=health) that had a checkmark at cors and api, I got searchability and audio playback running.

Now I guess, I have to figure out what codecs to install on my osmc to get the video.
