### ISSUE TITLE
 __class__ cell not found

### ISSUE THREAD

**Issue by innerspacepilot** [lekma/plugin.video.invidious#66]
Hello!
Plugin doesn't start on Kodi (20.0-ALPHA1 (19.90.101) Git:20211011-nogitfound). Platform: Linux ARM 32-bit,
Python3.10 on armv7

Error message:
`2021-10-12 22:50:24.035 T:9620     info <general>: initializing python engine.
2021-10-12 22:50:25.331 T:9620    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'RuntimeError'>
Error Contents: super(): __class__ cell not found
Traceback (most recent call last):
  File "/home/kodi/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 218, in <module>
    dispatch(*argv)
  File "/home/kodi/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 214, in dispatch
    InvidiousPlugin(url, int(handle)).dispatch(**parseQuery(query))
  File "/home/kodi/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 26, in dispatch
    super().dispatch(**kwargs)
RuntimeError: super(): __class__ cell not found
-->End of Python script error report<--

2021-10-12 22:50:25.503 T:9620     info <general>: Python interpreter stopped
2021-10-12 22:50:25.505 T:9618    error <general>: GetDirectory - Error getting plugin://plugin.video.invidious/
2021-10-12 22:50:25.535 T:8609    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.invidious/) failed
`

Thanks

**Comment by innerspacepilot** [comment]
version 1.0.8 is now working
Thanks :)
