### ISSUE TITLE
Error on opening channels

### ISSUE THREAD

**Issue by bjoern-vh** [lekma/plugin.video.invidious#78]
Hello,

unfortunately in version 1.0.23 not all channels can be opened without errors again. On many channels I get this error log:

```
2023-03-04 16:08:50.138 T:1070     info <general>: [plugin.video.invidious] <service.session> request: https://invidious.snopyta.org/api/v1/channels/UC5zBG6ZkA8NfC9cvxdvpPJA/videos?page=1&region=DE

2023-03-04 16:08:51.087 T:32717   error <general>: GetDirectory - Error getting plugin://plugin.video.invidious/?action=channel&authorId=UC5zBG6ZkA8NfC9cvxdvpPJA

2023-03-04 16:08:51.111 T:824     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.invidious/?action=channel&authorId=UC5zBG6ZkA8NfC9cvxdvpPJA) failed

2023-03-04 16:08:51.112 T:32718   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'continuation'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 218, in <module>
                                                       dispatch(*argv)
                                                     File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 214, in dispatch
                                                       InvidiousPlugin(url, int(handle)).dispatch(**parseQuery(query))
                                                     File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 26, in dispatch
                                                       super(InvidiousPlugin, self).dispatch(**kwargs)
                                                     File "/storage/.kodi/addons/script.module.iapc/lib/iapc/tools/plugin.py", line 66, in dispatch
                                                       return action(**kwargs)
                                                              ^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.iapc/lib/iapc/tools/plugin.py", line 33, in wrapper
                                                       raise error
                                                     File "/storage/.kodi/addons/script.module.iapc/lib/iapc/tools/plugin.py", line 30, in wrapper
                                                       success = func(self, **kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.invidious/lib/plugin.py", line 95, in channel
                                                       return self.addDirectory(client.channel(**kwargs), "video", **kwargs)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.invidious/lib/invidious/client.py", line 88, in channel
                                                       data["videos"], continuation=data["continuation"], category=category
                                                                                    ~~~~^^^^^^^^^^^^^^^^
                                                   KeyError: 'continuation'
                                                   -->End of Python script error report<--
```

For this example I have searched for the channel "Chris Washington" and used the first result. Youtube and Invidious have no problems.

This issue is on all tested public Invidious instances.

I am using Kodi 20 on LibreELEC Beta 2 for Raspberry Pi 4. Invidious addon in version 1.0.23.

**Comment by lekma** [comment]
please try 1.0.25

**Comment by bjoern-vh** [comment]
That looks great. Good job. Thanks a lot :-)
