### ISSUE TITLE
Invidios 1.0.14/1.0.13 on Matrix 19.5

### ISSUE THREAD

**Issue by netfiller** [lekma/plugin.video.invidious#84]
Hi,

i have a Kodi Matrix 19.5 installation an i try the invidios 1.0.13 and 1.0.14 with iapc script 1.0.2 on it.
This two are the latest versions for kodi 19.5. But when i will search a channel (on example cinenet) the plugin will find it, but i cant go in the channel.

`2023-04-19 17:06:27.844 T:12620   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.invidious/?action=channel&authorId=UClyuw-OWE6taGFv0reZI6eQ
2023-04-19 17:06:27.871 T:6916    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.invidious/?action=channel&authorId=UClyuw-OWE6taGFv0reZI6eQ) failed
2023-04-19 17:06:27.894 T:3836    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'getItem'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\plugin.video.invidious\lib\plugin.py", line 218, in <module>
                                                       dispatch(*argv)
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\plugin.video.invidious\lib\plugin.py", line 214, in dispatch
                                                       InvidiousPlugin(url, int(handle)).dispatch(**parseQuery(query))
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\plugin.video.invidious\lib\plugin.py", line 26, in dispatch
                                                       super(InvidiousPlugin, self).dispatch(**kwargs)
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\plugin.py", line 66, in dispatch
                                                       return action(**kwargs)
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\plugin.py", line 33, in wrapper
                                                       raise error
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\plugin.py", line 30, in wrapper
                                                       success = func(self, **kwargs)
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\plugin.video.invidious\lib\plugin.py", line 94, in channel
                                                       return self.addDirectory(client.channel(**kwargs), "video", **kwargs)
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\plugin.video.invidious\lib\plugin.py", line 66, in addDirectory
                                                       if super(InvidiousPlugin, self).addDirectory(items, *args):
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\plugin.py", line 98, in addDirectory
                                                       return self.addItems(items, *args)
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\plugin.py", line 83, in addItems
                                                       self.__handle__, [item.asItem() for item in items if item]
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\plugin.py", line 83, in <listcomp>
                                                       self.__handle__, [item.asItem() for item in items if item]
                                                     File "C:\Users\netfiller\AppData\Roaming\Kodi\addons\script.module.iapc\lib\iapc\tools\objects.py", line 79, in <genexpr>
                                                       return (item.getItem(*args) for item in self if item)
                                                   AttributeError: 'str' object has no attribute 'getItem'
                                                   -->End of Python script error report<--`

This is the error for enter the channel that i find. This is with all channel that i search.

Pls make invidios work again with kodi matrix. thx.

**Comment by DarthRaver** [comment]
I have the same problem. 
The feed is still working, but it's not possible to enter any channel any more (from addon or from favorites).
I would also like to have it fixed for matrix. Pretty please? :)

**Comment by lekma** [comment]
I won't be able to have a look before the week after next one, please, be patient.
(also, given that I can't test matrix anymore, I will rely on you guys testing)

**Comment by netfiller** [comment]
No problem, i check the version when its done ;)

**Comment by netfiller** [comment]
A little reminder for the problem with the channels in matrix version ;)

**Comment by lekma** [comment]
@netfiller: can you post a pastebin of the log when the error happen, please?

**Comment by lekma** [comment]
can you give the [matrix](https://github.com/lekma/plugin.video.invidious/tree/matrix) branch a try and report?
thanks for your help

**Comment by netfiller** [comment]
The matrix branch is working now ;) thx!
You are great.

**Comment by lekma** [comment]
@netfiller: can you please test v1.0.18 and tell me if it is ok?
thanks again for the help

**Comment by netfiller** [comment]
1.0.18 working great. Thx.

**Comment by DarthRaver** [comment]
@lekma 
Sorry it took so long, i moved, had no internet, it was real fun. 
But now that i sometimes have some internet, i can report that v1.0.18 seems to work great.
Thanks for fixing it!
